/*

 HUBMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\alive\Desktop\Dev\Wrath\BGSheet.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define HubMapWidth 20
#define HubMapHeight 18
#define HubMapBank 0

extern unsigned char HubMap[];

/* End of HUBMAP.H */
